'use client'

import { jsPDF } from 'jspdf'
import { useMemo, useState, useTransition, type CSSProperties } from 'react'
import type { ReportApiPayload } from '@/app/api/report/route'

export type ReportDogOption = {
  id: string
  name: string
}

const GREEN = '#2d7a4f'
const GREEN_RGB: [number, number, number] = [45, 122, 79]

const cardStyle: CSSProperties = {
  backgroundColor: '#ffffff',
  border: '1px solid #e5e7eb',
}

function lastSixMonths(): { value: string; label: string }[] {
  const out: { value: string; label: string }[] = []
  const now = new Date()
  for (let i = 0; i < 6; i++) {
    const d = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() - i, 1))
    const y = d.getUTCFullYear()
    const m = d.getUTCMonth() + 1
    const value = `${y}-${String(m).padStart(2, '0')}`
    const label = new Intl.DateTimeFormat('en-GB', {
      month: 'long',
      year: 'numeric',
      timeZone: 'UTC',
    }).format(d)
    out.push({ value, label })
  }
  return out
}

function defaultMonthValue(): string {
  const d = new Date()
  return `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, '0')}`
}

function trunc(s: string, max: number): string {
  const t = s.replace(/\s+/g, ' ').trim()
  if (t.length <= max) return t
  return `${t.slice(0, max - 1)}…`
}

function formatDate(s: string): string {
  const d = new Date(s)
  if (Number.isNaN(d.getTime())) return s.slice(0, 10)
  return d.toISOString().slice(0, 10)
}

function formatDue(s: string): string {
  return formatDate(s)
}

function buildPdf(payload: ReportApiPayload) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const pageW = doc.internal.pageSize.getWidth()
  const margin = 20
  let y = margin

  const newPage = () => {
    doc.addPage()
    y = margin
  }

  const ensure = (h: number) => {
    if (y + h > 280) newPage()
  }

  const footer = () => {
    ensure(12)
    doc.setFontSize(8)
    doc.setTextColor(100, 100, 100)
    doc.setFont('helvetica', 'italic')
    doc.text('Generated by DogOS • Always consult a licensed veterinarian', margin, 292)
    doc.setFont('helvetica', 'normal')
  }

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  doc.setTextColor(...GREEN_RGB)
  doc.text('DogOS Health Report', margin, y)
  y += 12

  doc.setFontSize(11)
  doc.setTextColor(0, 0, 0)
  doc.setFont('helvetica', 'normal')
  doc.text(`Dog: ${payload.dog.name}`, margin, y)
  y += 6
  doc.text(`Breed: ${payload.dog.breed}`, margin, y)
  y += 6
  doc.text(`Age: ${payload.dog.age}`, margin, y)
  y += 6
  doc.text(`Report period: ${payload.periodLabel}`, margin, y)
  y += 6
  doc.text(`Generated: ${new Date().toISOString().slice(0, 10)}`, margin, y)
  y += 10

  ensure(24)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.text('Executive Summary', margin, y)
  y += 6
  const exLines: string[] = doc.splitTextToSize(
    payload.summary.executive_summary,
    pageW - 2 * margin,
  )
  const boxH = 6 + exLines.length * 5
  ensure(boxH + 4)
  doc.setFillColor(243, 244, 246)
  doc.rect(margin, y, pageW - 2 * margin, boxH, 'F')
  doc.setTextColor(55, 65, 81)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  let ty = y + 6
  exLines.forEach((line: string) => {
    doc.text(line, margin + 3, ty)
    ty += 5
  })
  y += boxH + 8

  const weightRows = payload.weight_logs
  const weightTrend =
    weightRows.length >= 2
      ? `${weightRows[weightRows.length - 1].weight_kg - weightRows[0].weight_kg >= 0 ? 'Gained' : 'Lost'} ${Math.abs(weightRows[weightRows.length - 1].weight_kg - weightRows[0].weight_kg).toFixed(1)} kg this month (first vs last weigh-in).`
      : weightRows.length === 1
        ? 'Single weigh-in recorded this month.'
        : 'No weight entries this month.'

  ensure(16)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.setTextColor(0, 0, 0)
  doc.text('Weight', margin, y)
  y += 7
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.text(`Trend: ${weightTrend}`, margin, y)
  y += 6
  for (const line of doc.splitTextToSize(payload.summary.weight_summary, pageW - 2 * margin)) {
    ensure(6)
    doc.text(line, margin, y)
    y += 5
  }
  y += 4

  ensure(8)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.text('Date', margin, y)
  doc.text('Weight (kg)', margin + 38, y)
  doc.text('Notes', margin + 70, y)
  y += 5
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setDrawColor(200, 200, 200)
  doc.line(margin, y, pageW - margin, y)
  y += 4
  for (const w of weightRows) {
    ensure(8)
    doc.text(formatDate(w.logged_at), margin, y)
    doc.text(String(w.weight_kg), margin + 38, y)
    doc.text(trunc(w.notes ?? '—', 40), margin + 70, y)
    y += 6
  }
  y += 6

  const totalActivity = payload.activity_logs.length
  const totalMinutes = payload.activity_logs.reduce((s, a) => s + a.duration_minutes, 0)

  ensure(20)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.text('Activity', margin, y)
  y += 7
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.text(
    `Total: ${totalActivity} activities, ${totalMinutes} total minutes`,
    margin,
    y,
  )
  y += 6
  for (const line of doc.splitTextToSize(payload.summary.activity_summary, pageW - 2 * margin)) {
    ensure(6)
    doc.text(line, margin, y)
    y += 5
  }
  y += 4

  ensure(8)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.text('Date', margin, y)
  doc.text('Type', margin + 32, y)
  doc.text('Min', margin + 72, y)
  doc.text('Intensity', margin + 95, y)
  y += 5
  doc.setDrawColor(200, 200, 200)
  doc.line(margin, y, pageW - margin, y)
  y += 4
  doc.setFont('helvetica', 'normal')
  for (const a of payload.activity_logs) {
    ensure(8)
    doc.text(formatDate(a.logged_at), margin, y)
    doc.text(trunc(a.activity_type, 18), margin + 32, y)
    doc.text(String(a.duration_minutes), margin + 72, y)
    doc.text(trunc(a.intensity ?? '—', 12), margin + 95, y)
    y += 6
  }
  y += 6

  ensure(16)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.text('Health Log', margin, y)
  y += 7
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  for (const line of doc.splitTextToSize(payload.summary.health_summary, pageW - 2 * margin)) {
    ensure(6)
    doc.text(line, margin, y)
    y += 5
  }
  y += 4

  ensure(8)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.text('Date', margin, y)
  doc.text('Mood', margin + 28, y)
  doc.text('Appetite', margin + 52, y)
  doc.text('Energy', margin + 80, y)
  doc.text('Stool', margin + 105, y)
  y += 4
  doc.line(margin, y, pageW - margin, y)
  y += 4
  doc.setFont('helvetica', 'normal')
  for (const h of payload.health_logs) {
    ensure(8)
    doc.text(h.log_date, margin, y)
    doc.text(trunc(h.mood ?? '—', 10), margin + 28, y)
    doc.text(trunc(h.appetite ?? '—', 10), margin + 52, y)
    doc.text(trunc(h.energy ?? '—', 10), margin + 80, y)
    doc.text(trunc(h.stool ?? '—', 14), margin + 105, y)
    y += 6
  }
  y += 6

  if (payload.symptom_checks.length > 0) {
    ensure(14)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(12)
    doc.text('Symptom Checks', margin, y)
    y += 7
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(8)
    doc.text('Date', margin, y)
    doc.text('Symptoms', margin + 28, y)
    doc.text('AI Assessment', margin + 90, y)
    doc.text('Priority', margin + 155, y)
    y += 4
    doc.line(margin, y, pageW - margin, y)
    y += 4
    doc.setFont('helvetica', 'normal')
    for (const s of payload.symptom_checks) {
      ensure(14)
      doc.text(formatDate(s.created_at), margin, y)
      doc.text(trunc(s.symptoms, 22), margin + 28, y)
      doc.text(trunc(s.title, 28), margin + 90, y)
      doc.text(trunc(s.triage_level, 12), margin + 155, y)
      y += 6
    }
    y += 6
  }

  ensure(14)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.text('Upcoming Reminders', margin, y)
  y += 7
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.text('Type', margin, y)
  doc.text('Title', margin + 35, y)
  doc.text('Due date', margin + 120, y)
  y += 5
  doc.line(margin, y, pageW - margin, y)
  y += 4
  doc.setFont('helvetica', 'normal')
  for (const r of payload.reminders) {
    ensure(8)
    doc.text(trunc(r.type, 12), margin, y)
    doc.text(trunc(r.title, 40), margin + 35, y)
    doc.text(formatDue(r.due_at), margin + 120, y)
    y += 6
  }
  y += 8

  ensure(30)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(0, 0, 0)
  doc.text('Clinical summary (AI)', margin, y)
  y += 7
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  const concerns = payload.summary.concerns.length
    ? `Concerns: ${payload.summary.concerns.join('; ')}`
    : 'Concerns: none noted.'
  const pos = payload.summary.positive_notes.length
    ? `Positive notes: ${payload.summary.positive_notes.join('; ')}`
    : ''
  const vet = `Vet talking points: ${payload.summary.vet_talking_points.join('; ')}`
  const block = [concerns, pos, vet].filter(Boolean).join('\n\n')
  const lines: string[] = doc.splitTextToSize(block, pageW - 2 * margin)
  lines.forEach((line: string) => {
    ensure(6)
    doc.text(line, margin, y)
    y += 5
  })

  footer()

  const safeName = payload.dog.name.replace(/[^\w\s-]/g, '').trim() || 'dog'
  doc.save(`DogOS-Report-${safeName}-${payload.month}.pdf`)
}

type ReportClientProps = {
  dogs: ReportDogOption[]
}

export default function ReportClient({ dogs }: ReportClientProps) {
  const monthOptions = useMemo(() => lastSixMonths(), [])
  const [dogId, setDogId] = useState(dogs[0]?.id ?? '')
  const [month, setMonth] = useState(defaultMonthValue())
  const [pending, startTransition] = useTransition()
  const [error, setError] = useState<string | null>(null)

  function generate() {
    setError(null)
    if (!dogId || !month) {
      setError('Please select a dog and month.')
      return
    }
    startTransition(async () => {
      const res = await fetch('/api/report', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ dogId, month }),
      })
      const json = (await res.json().catch(() => null)) as
        | ReportApiPayload
        | { error?: string; message?: string }
        | null

      if (!res.ok) {
        const msg =
          json && typeof json === 'object' && 'message' in json && json.message
            ? String((json as { message: string }).message)
            : json && typeof json === 'object' && 'error' in json
              ? String((json as { error: string }).error)
              : 'Request failed'
        setError(msg)
        return
      }
      buildPdf(json as ReportApiPayload)
    })
  }

  return (
    <div className="mx-auto max-w-2xl px-4 py-6">
      <header className="mb-6">
        <h1 className="text-2xl font-bold" style={{ color: '#111827' }}>
          📋 Monthly Health Report
        </h1>
        <p className="mt-1 text-sm" style={{ color: '#6b7280' }}>
          Generate a PDF summary of your dog&apos;s health data for your vet
        </p>
      </header>

      <div className="rounded-2xl p-6" style={cardStyle}>
        <label className="block text-sm font-medium" style={{ color: '#374151' }}>
          Dog
        </label>
        <select
          className="mt-1 w-full rounded-lg border border-gray-200 px-3 py-2 text-sm"
          value={dogId}
          onChange={(e) => setDogId(e.target.value)}
          disabled={dogs.length === 0}
        >
          {dogs.length === 0 ? (
            <option value="">No dogs yet — add a dog first</option>
          ) : (
            dogs.map((d) => (
              <option key={d.id} value={d.id}>
                {d.name}
              </option>
            ))
          )}
        </select>

        <label className="mt-4 block text-sm font-medium" style={{ color: '#374151' }}>
          Month
        </label>
        <select
          className="mt-1 w-full rounded-lg border border-gray-200 px-3 py-2 text-sm"
          value={month}
          onChange={(e) => setMonth(e.target.value)}
        >
          {monthOptions.map((m) => (
            <option key={m.value} value={m.value}>
              {m.label}
            </option>
          ))}
        </select>

        <div className="mt-6" style={{ borderTop: '1px solid #e5e7eb', paddingTop: '20px' }}>
          <p className="text-sm font-semibold" style={{ color: '#111827' }}>
            What&apos;s included
          </p>
          <ul className="mt-3 space-y-2 text-sm" style={{ color: '#374151' }}>
            <li>✅ Weight measurements and trend</li>
            <li>✅ Daily health logs (mood, appetite, energy)</li>
            <li>✅ Activity summary (total minutes, types)</li>
            <li>✅ Symptom checks and AI assessments</li>
            <li>✅ Upcoming reminders</li>
          </ul>
        </div>

        <button
          type="button"
          className="mt-6 w-full rounded-xl py-3 text-sm font-semibold text-white disabled:opacity-50"
          style={{ backgroundColor: GREEN }}
          disabled={pending || dogs.length === 0}
          onClick={generate}
        >
          Generate & Download PDF
        </button>
      </div>

      {pending ? (
        <p className="mt-8 text-center text-sm font-medium" style={{ color: '#374151' }}>
          📄 Generating your report...
        </p>
      ) : null}

      {error ? (
        <div
          className="mt-6 rounded-xl border px-4 py-3 text-sm"
          style={{ borderColor: '#fecaca', backgroundColor: '#fef2f2', color: '#991b1b' }}
        >
          {error}
        </div>
      ) : null}
    </div>
  )
}
